export function slideLine(values){const a=values.filter(Boolean),out=[],score={v:0};for(let i=0;i<a.length;i++){if(a[i]===a[i+1]){out.push(a[i]*2);score.v+=a[i]*2;i++}else out.push(a[i])}while(out.length<values.length)out.push(0);return{line:out,score:score.v}}
const transpose=b=>b[0].map((_,i)=>b.map(r=>r[i]));
export function traceMove(board,dir){const out=Array.from({length:4},()=>Array(4).fill(0)),motions=[];let score=0;for(let line=0;line<4;line++){const coords=Array.from({length:4},(_,i)=>dir==='left'?[line,i]:dir==='right'?[line,3-i]:dir==='up'?[i,line]:[3-i,line]);const items=coords.map(c=>({from:c,value:board[c[0]][c[1]]})).filter(i=>i.value);let dest=0;for(let i=0;i<items.length;i++){const pair=items[i+1]?.value===items[i].value,target=coords[dest++],result=pair?items[i].value*2:items[i].value;motions.push({from:items[i].from,to:target,value:items[i].value,result});if(pair){motions.push({from:items[i+1].from,to:target,value:items[i+1].value,result});score+=result;i++}out[target[0]][target[1]]=result}}return{board:out,score,changed:JSON.stringify(out)!==JSON.stringify(board),motions}}
export function moveBoard(board,dir){const {board:b,score,changed}=traceMove(board,dir);return{board:b,score,changed}}
export function canMove(b){if(b.some(r=>r.includes(0)))return true;return b.some((r,y)=>r.some((v,x)=>b[y]?.[x+1]===v||b[y+1]?.[x]===v))}
export function milestonesCrossed(before,after){return[128,256,512,1024,2048].filter(v=>before<v&&after>=v)}
export function restoreUndo(snapshot){return{board:snapshot.board.map(r=>[...r]),score:snapshot.score}}
export function create2048Controller({storage,progression=null,random=Math.random}){let root,b,score,won=false,touch=null,animating=false,animationTimer,undoState=null,runState={paid:new Set()};
 function spawn(){const open=[];b.forEach((r,y)=>r.forEach((v,x)=>{if(!v)open.push([y,x])}));if(open.length){const[y,x]=open[Math.floor(random()*open.length)];b[y][x]=random()<.9?2:4}}
 function reset(){if(progression?.snapshot().active.game2048==='undo')progression.refund('game2048');b=Array.from({length:4},()=>Array(4).fill(0));score=0;won=false;undoState=null;runState={paid:new Set()};spawn();spawn();hide();render()}
 function move(dir){if(animating)return;const m=traceMove(b,dir);if(!m.changed)return;const beforeMax=Math.max(...b.flat());if(progression?.snapshot().active.game2048==='undo'&&!undoState)undoState={board:b.map(r=>[...r]),score};animating=true;animate(m.motions);score+=m.score;animationTimer=setTimeout(()=>{b=m.board;spawn();animating=false;for(const tile of milestonesCrossed(beforeMax,Math.max(...b.flat())))progression?.earn({game:'game2048',tile},runState);render();if(!won&&b.flat().includes(2048)){won=true;show('You made 2048!')}else if(!canMove(b))show('No more moves!')},180)}
 function base(){return Array.from({length:16},(_,i)=>`<span class="g-bg" style="--x:${i%4};--y:${Math.floor(i/4)}"></span>`).join('')}
 function tile(v,y,x,extra=''){return `<i class="g-tile n${v} ${extra}" style="--x:${x};--y:${y}">${v}</i>`}
 function render(){const board=root.querySelector('[data-g-board]');board.innerHTML=base()+b.flatMap((r,y)=>r.map((v,x)=>v?tile(v,y,x):'')).join('');root.querySelector('[data-g-score]').textContent=score;root.querySelector('[data-g-action="undo"]').hidden=!undoState;const best=Math.max(score,storage.get('2048Best',0));root.querySelector('[data-g-best]').textContent=best;storage.set('2048Best',best)}
 function animate(motions){const board=root.querySelector('[data-g-board]'),size=(board.clientWidth-54)/4;board.innerHTML=base()+motions.map((m,i)=>`<i class="g-tile moving n${m.value}" style="--x:${m.to[1]};--y:${m.to[0]};--dx:${(m.from[1]-m.to[1])*(size+10)}px;--dy:${(m.from[0]-m.to[0])*(size+10)}px">${m.value}</i>`).join('');requestAnimationFrame(()=>board.querySelectorAll('.moving').forEach(t=>t.classList.add('go')))}
 function show(s){root.querySelector('[data-g-message]').textContent=s;root.querySelector('[data-g-overlay]').hidden=false}function hide(){root.querySelector('[data-g-overlay]').hidden=true}
 const click=e=>{const d=e.target.closest('[data-g-dir]')?.dataset.gDir,a=e.target.closest('[data-g-action]')?.dataset.gAction;if(d)move(d);if(a==='restart')reset();if(a==='continue')hide();if(a==='undo'&&undoState){({board:b,score}=restoreUndo(undoState));undoState=null;progression?.consume('game2048','undo');render()}};const key=e=>{const d={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'}[e.key];if(d){e.preventDefault();move(d)}};const start=e=>touch=[e.clientX,e.clientY];const end=e=>{if(!touch)return;const dx=e.clientX-touch[0],dy=e.clientY-touch[1];if(Math.max(Math.abs(dx),Math.abs(dy))>30)move(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));touch=null};
 return{mount(r){root=r;root.addEventListener('click',click);root.querySelector('[data-g-board]').addEventListener('pointerdown',start);root.querySelector('[data-g-board]').addEventListener('pointerup',end);window.addEventListener('keydown',key);reset()},pause(){},resume(){},destroy(){clearTimeout(animationTimer);if(progression?.snapshot().active.game2048==='undo')progression.refund('game2048');root?.removeEventListener('click',click);window.removeEventListener('keydown',key);root=null}}}

