export const BOOSTS={slowTime:{name:'Slow Time',cost:60,game:'tetris',icon:'⏳',effect:'Slower falling for 30 seconds'},undo:{name:'Undo',cost:50,game:'game2048',icon:'↶',effect:'Undo one valid move'},shield:{name:'Shield',cost:50,game:'obby',icon:'◆',effect:'Block one hazard death'},doublePoints:{name:'Double Points',cost:75,game:'any',icon:'×2',effect:'Double your next reward'}};
const empty=()=>({version:1,points:0,inventory:{slowTime:0,undo:0,shield:0,doublePoints:0},active:{tetris:null,game2048:null,obby:null}});
const count=v=>Number.isFinite(v)&&v>0?Math.floor(v):0;
export function normalizeProgression(value){const out=empty();if(!value||typeof value!=='object')return out;out.points=count(value.points);for(const k of Object.keys(out.inventory))out.inventory[k]=count(value.inventory?.[k]);for(const k of Object.keys(out.active)){const id=value.active?.[k];out.active[k]=BOOSTS[id]&&(BOOSTS[id].game===k||BOOSTS[id].game==='any')?id:null}return out}
export function rewardFor(e){if(e.game==='tetris')return({1:5,2:15,3:30,4:50}[e.rows]||0);if(e.game==='game2048')return({128:10,256:20,512:40,1024:80,2048:160}[e.tile]||0);if(e.game==='obby'&&Number.isInteger(e.level))return 30+(e.noDeath?15:0);return 0}
export function createProgression({storage,notify=()=>{}}){let state=normalizeProgression(storage.get('progression',empty())),listeners=[];
 const save=(type,detail={})=>{storage.set('progression',state);const event={type,...detail,state:snapshot()};listeners.forEach(fn=>fn(event));notify(event)};const snapshot=()=>structuredClone(state);
 function earn(event,run={}){let key;if(event.game==='game2048')key=`2048:${event.tile}`;if(event.game==='obby')key=`obby:${event.level}`;if(key){run.paid??=new Set();if(run.paid.has(key))return 0;run.paid.add(key)}let amount=rewardFor(event);if(!amount)return 0;const doubleGame=Object.keys(state.active).find(g=>state.active[g]==='doublePoints');if(doubleGame){amount*=2;state.active[doubleGame]=null}state.points+=amount;save('earn',{amount,label:event.game});return amount}
 function purchase(id){const b=BOOSTS[id];if(!b||state.points<b.cost)return false;state.points-=b.cost;state.inventory[id]++;save('purchase',{boost:id});return true}
 function activate(game,id){const b=BOOSTS[id];if(!b||!state.inventory[id]||state.active[game]||(b.game!==game&&b.game!=='any'))return false;state.inventory[id]--;state.active[game]=id;save('activate',{game,boost:id});return true}
 function consume(game,id){if(state.active[game]!==id)return false;state.active[game]=null;save('consume',{game,boost:id});return true}
 function refund(game){const id=state.active[game];if(!id)return false;state.active[game]=null;state.inventory[id]++;save('refund',{game,boost:id});return true}
 return{snapshot,earn,purchase,activate,consume,refund,subscribe(fn){listeners.push(fn);return()=>listeners=listeners.filter(x=>x!==fn)}}}

