export const SHAPES=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]]];
export function rotate(m){return m[0].map((_,i)=>m.map(r=>r[i]).reverse())}
export function collides(b,p,x,y){return p.some((r,dy)=>r.some((v,dx)=>v&&(x+dx<0||x+dx>=b[0].length||y+dy>=b.length||(y+dy>=0&&b[y+dy][x+dx]))))}
export function clearRows(board){const keep=board.filter(r=>r.some(v=>!v)),cleared=board.length-keep.length;return{cleared,board:[...Array.from({length:cleared},()=>Array(board[0].length).fill(0)),...keep]}}
export function lineScore(n,l){return ([0,100,300,500,800][n]||0)*l}
export function rotationReady(last,now,cooldown=500){return now-last>=cooldown}
export function slowInterval(interval,active){return active?interval*1.6:interval}
export function createTetrisController({storage,progression=null}){let root,b,cur,next,x,y,score,lines,level,timer,paused=false,bag=[],lastRotate=-Infinity,slowUntil=0;
 const els=()=>({board:root.querySelector('[data-t-board]'),next:root.querySelector('[data-t-next]')});
 const piece=()=>{if(!bag.length)bag=[0,1,2,3,4,5,6].sort(()=>Math.random()-.5);const id=bag.pop();return{m:SHAPES[id],c:id+1}}
 function reset(){b=Array.from({length:20},()=>Array(10).fill(0));score=lines=0;level=1;next=piece();paused=false;spawn();root.querySelector('[data-t-overlay]').hidden=true;render();loop()}
 function spawn(){if(progression?.snapshot().active.tetris==='slowTime'){progression.consume('tetris','slowTime');slowUntil=performance.now()+30000}cur=next;next=piece();x=3;y=-1;if(collides(b,cur.m,x,y)){pause();show('Stack topped out!')}}
 function lock(){cur.m.forEach((r,dy)=>r.forEach((v,dx)=>{if(v&&y+dy>=0)b[y+dy][x+dx]=cur.c}));const r=clearRows(b);b=r.board;lines+=r.cleared;level=1+Math.floor(lines/10);score+=lineScore(r.cleared,level);if(r.cleared)progression?.earn({game:'tetris',rows:r.cleared},{});spawn()}
 function step(){if(!collides(b,cur.m,x,y+1))y++;else lock();render()}
 function act(a){if(paused&&a!=='pause'&&a!=='restart')return;if(a==='left'&&!collides(b,cur.m,x-1,y))x--;if(a==='right'&&!collides(b,cur.m,x+1,y))x++;if(a==='down'){step();score++}if(a==='drop'){let n=0;while(!collides(b,cur.m,x,y+1)){y++;n++}score+=n*2;lock()}if(a==='rotate'){const now=performance.now();if(!rotationReady(lastRotate,now))return;lastRotate=now;const m=rotate(cur.m),kick=[0,-1,1,-2,2].find(k=>!collides(b,m,x+k,y));if(kick!==undefined){cur.m=m;x+=kick}const btn=root.querySelector('[data-t-action="rotate"]');btn?.classList.add('cooling');setTimeout(()=>btn?.classList.remove('cooling'),500)}if(a==='pause'){paused=!paused;paused?pause():loop()}if(a==='restart')reset();render()}
 function render(){if(!root)return;const view=b.map(r=>[...r]);cur?.m.forEach((r,dy)=>r.forEach((v,dx)=>{if(v&&y+dy>=0&&view[y+dy])view[y+dy][x+dx]=cur.c}));els().board.innerHTML=view.flat().map(v=>`<i class="c${v}"></i>`).join('');els().next.innerHTML=next.m.flatMap(r=>r.map(v=>`<i class="c${v?next.c:0}"></i>`)).join('');for(const[k,v]of Object.entries({score,lines,level,best:Math.max(score,storage.get('tetrisBest',0))}))root.querySelector(`[data-t-${k}]`).textContent=v;storage.set('tetrisBest',Math.max(score,storage.get('tetrisBest',0)))}
 function loop(){clearTimeout(timer);if(!paused){const base=Math.max(120,800-level*65),slow=performance.now()<slowUntil;timer=setTimeout(()=>{step();loop()},slowInterval(base,slow));const boost=root?.querySelector('[data-t-boost-status]');if(boost)boost.textContent=slow?`Slow Time ${Math.ceil((slowUntil-performance.now())/1000)}s`:''}}function pause(){paused=true;clearTimeout(timer)}function show(m){root.querySelector('[data-t-message]').textContent=m;root.querySelector('[data-t-overlay]').hidden=false}
 const click=e=>{const a=e.target.closest('[data-t-action]')?.dataset.tAction;if(a)act(a)};const key=e=>{const a={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'rotate',w:'rotate',ArrowDown:'down',s:'down',' ':'drop',p:'pause'}[e.key];if(a){e.preventDefault();act(a)}};
 return{mount(r){root=r;root.addEventListener('click',click);window.addEventListener('keydown',key);reset()},pause,resume(){paused=false;loop()},destroy(){pause();if(progression?.snapshot().active.tetris==='slowTime')progression.refund('tetris');root?.removeEventListener('click',click);window.removeEventListener('keydown',key);root=null}}}

